spring :
  datasource :
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/auth?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username : root
    password : 123456
#    platform: mysql
#    schema: classpath:/schema.sql
#    initialization-mode: always
mybatis :
  config-location : classpath:/mybatis-config.xml
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "